### ISSUE TITLE
Tasks for the process calculations effort

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/vxDataProcessor#4]
## Tasks for the process calculations effort

```[tasklist]
### Process Calculation Tasks
- [ ] #12
- [x] Hook API service up to the manager calculation layer
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/5
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/13
- [x] Determine do we use AWS lambdas or do we use internal server? How do we do this?
- [x] Implement scorecard builders as Go thread workers.
- [x] Implement calculations - AWS Lamdas or go routines.
- [x] Implement director's Couchbase scorecard update mechanism.
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/28
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/29
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/30
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/33
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/31
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/32
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/39
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/40
- [ ] https://github.com/NOAA-GSL/vxDataProcessor/issues/58
```

**Comment by randytpierce** [comment]
All of the initial tasks are now finished and remaining issues are going to be treated as issues going forward so we can now close this issue.
